// Single source of truth. `provideAppInitializer` in app.config.ts calls
// `FaIconLibrary.addIcons(...APP_ICONS)` at bootstrap; every icon listed below
// is then referenceable from any template by its kebab-case name.
//
// The three parallel listings are structural — named `export…from` keeps
// tree-shaking working, the `import` is needed to build the runtime array.

export {
  faArrowLeft,
  faArrowRight,
  faBiohazard,
  faBrain,
  faCheck,
  faCircleCheck,
  faCircleInfo,
  faClipboard,
  faClipboardList,
  faCloudArrowUp,
  faDatabase,
  faDna,
  faDownload,
  faFlask,
  faHeartPulse,
  faIndustry,
  faLeaf,
  faLocationDot,
  faPersonWalking,
  faPrint,
  faRotateLeft,
  faShieldHalved,
  faTint,
  faTriangleExclamation,
  faUser,
} from '@fortawesome/free-solid-svg-icons';

import {
  faArrowLeft,
  faArrowRight,
  faBiohazard,
  faBrain,
  faCheck,
  faCircleCheck,
  faCircleInfo,
  faClipboard,
  faClipboardList,
  faCloudArrowUp,
  faDatabase,
  faDna,
  faDownload,
  faFlask,
  faHeartPulse,
  faIndustry,
  faLeaf,
  faLocationDot,
  faPersonWalking,
  faPrint,
  faRotateLeft,
  faShieldHalved,
  faTint,
  faTriangleExclamation,
  faUser,
} from '@fortawesome/free-solid-svg-icons';

export const APP_ICONS = [
  faArrowLeft,
  faArrowRight,
  faBiohazard,
  faBrain,
  faCheck,
  faCircleCheck,
  faCircleInfo,
  faClipboard,
  faClipboardList,
  faCloudArrowUp,
  faDatabase,
  faDna,
  faDownload,
  faFlask,
  faHeartPulse,
  faIndustry,
  faLeaf,
  faLocationDot,
  faPersonWalking,
  faPrint,
  faRotateLeft,
  faShieldHalved,
  faTint,
  faTriangleExclamation,
  faUser,
] as const;
